export const simplemaps_countrymap_mapdata = {
    main_settings: {
        // General settings
        width: "responsive",
        background_color: "#FFFFFF",
        background_transparent: "yes",
        border_color: "#ffffff",
        // State defaults
        state_description: "State description",
        state_color: "#88A4BC",
        state_hover_color: "#3B729F",
        state_url: "",
        border_size: 1.5,
        all_states_inactive: "no",
        all_states_zoomable: "yes",
        // Location defaults
        location_description: "Location description",
        location_url: "",
        location_color: "#FF0067",
        location_opacity: 0.8,
        location_hover_opacity: 1,
        location_size: 25,
        location_type: "square",
        location_image_source: "frog.png",
        location_border_color: "#FFFFFF",
        location_border: 2,
        location_hover_border: 2.5,
        all_locations_inactive: "no",
        all_locations_hidden: "no",
        // Label defaults
        label_color: "#ffffff",
        label_hover_color: "#ffffff",
        label_size: 16,
        label_font: "Arial",
        label_display: "auto",
        label_scale: "yes",
        hide_labels: "no",
        hide_eastern_labels: "no",
        // Zoom settings
        zoom: "yes",
        manual_zoom: "yes",
        back_image: "no",
        initial_back: "no",
        initial_zoom: "-1",
        initial_zoom_solo: "no",
        region_opacity: 1,
        region_hover_opacity: 0.6,
        zoom_out_incrementally: "yes",
        zoom_percentage: 0.99,
        zoom_time: 0.5,
        // Popup settings
        popup_color: "white",
        popup_opacity: 0.9,
        popup_shadow: 1,
        popup_corners: 5,
        popup_font: "12px/1.5 Verdana, Arial, Helvetica, sans-serif",
        popup_nocss: "no",
        // Advanced settings
        div: "map",
        auto_load: "yes",
        url_new_tab: "no",
        images_directory: "default",
        fade_time: 0.1,
        link_text: "View Website",
        popups: "detect",
        state_image_url: "",
        state_image_position: "",
        location_image_url: "",
    },
    state_specific: {
        AFBAL: { name: "Balkh", color: "#15e89b" },
        AFBAM: { name: "Bamyan" },
        AFBDG: { name: "Badghis" },
        AFBDS: { name: "Badakhshan" },
        AFBGL: { name: "Baghlan" },
        AFFRA: { name: "Farah" },
        AFFYB: { name: "Faryab" },
        AFGHA: { name: "Ghazni" },
        AFGHO: { name: "Ghor" },
        AFHEL: { name: "Hilmand" },
        AFHER: { name: "Hirat" },
        AFJOW: { name: "Jawzjan" },
        AFKAB: { name: "Kabul" },
        AFKAN: { name: "Kandahar" },
        AFKAP: { name: "Kapisa" },
        AFKDZ: { name: "Kunduz" },
        AFKHO: { name: "Khost" },
        AFKNR: { name: "Kunar" },
        AFLAG: { name: "Laghman" },
        AFLOG: { name: "Logar" },
        AFNAN: { name: "Nangarhar" },
        AFNIM: { name: "Nimroz" },
        AFNUR: { name: "Nuristan" },
        AFPAR: { name: "Parwan" },
        AFPIA: { name: "Paktika" },
        AFPKA: { name: "Paktya" },
        AFSAM: { name: "Samangan" },
        AFSAR: { name: "Sari Pul" },
        AFTAK: { name: "Takhar" },
        AFURU: { name: "Uruzgan" },
        AFWAR: { name: "Wardak" },
        AFZAB: { name: "Zabul" },
    },
    locations: {
        0: { name: "Kabul", lat: "34.516667", lng: "69.183333" },
    },
    labels: {
        AFBAL: { name: "Balkh", parent_id: "AFBAL" },
        AFBAM: { name: "Bamyan", parent_id: "AFBAM" },
        AFBDG: { name: "Badghis", parent_id: "AFBDG" },
        AFBDS: { name: "Badakhshan", parent_id: "AFBDS" },
        AFBGL: { name: "Baghlan", parent_id: "AFBGL" },
        AFFRA: { name: "Farah", parent_id: "AFFRA" },
        AFFYB: { name: "Faryab", parent_id: "AFFYB" },
        AFGHA: { name: "Ghazni", parent_id: "AFGHA" },
        AFGHO: { name: "Ghor", parent_id: "AFGHO" },
        AFHEL: { name: "Hilmand", parent_id: "AFHEL" },
        AFHER: { name: "Hirat", parent_id: "AFHER" },
        AFJOW: { name: "Jawzjan", parent_id: "AFJOW" },
        AFKAB: { name: "Kabul", parent_id: "AFKAB" },
        AFKAN: { name: "Kandahar", parent_id: "AFKAN" },
        AFKAP: { name: "Kapisa", parent_id: "AFKAP" },
        AFKDZ: { name: "Kunduz", parent_id: "AFKDZ" },
        AFKHO: { name: "Khost", parent_id: "AFKHO" },
        AFKNR: { name: "Kunar", parent_id: "AFKNR" },
        AFLAG: { name: "Laghman", parent_id: "AFLAG" },
        AFLOG: { name: "Logar", parent_id: "AFLOG" },
        AFNAN: { name: "Nangarhar", parent_id: "AFNAN" },
        AFNIM: { name: "Nimroz", parent_id: "AFNIM" },
        AFNUR: { name: "Nuristan", parent_id: "AFNUR" },
        AFPAR: { name: "Parwan", parent_id: "AFPAR" },
        AFPIA: { name: "Paktika", parent_id: "AFPIA" },
        AFPKA: { name: "Paktya", parent_id: "AFPKA" },
        AFSAM: { name: "Samangan", parent_id: "AFSAM" },
        AFSAR: { name: "Sari Pul", parent_id: "AFSAR" },
        AFTAK: { name: "Takhar", parent_id: "AFTAK" },
        AFURU: { name: "Uruzgan", parent_id: "AFURU" },
        AFWAR: { name: "Wardak", parent_id: "AFWAR" },
        AFZAB: { name: "Zabul", parent_id: "AFZAB" },
    },
    legend: {
        entries: [],
    },
    regions: {},
};
